version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: my_cv_maker
      DB_USERNAME: root
      DB_PASSWORD: pass
      APP_ENV: production
      APP_DEBUG: false
      APP_KEY: base64:H0Wp1SpxWFrPYFN9Ud+wU2gGY1rsTLKI9KeF4hbg52c=
      APP_URL: "https://your-render-app-url.onrender.com"
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: my_cv_maker
      MYSQL_USER: root
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
